export const downloadUrl = {
  // 合同管理
  CONTRACT_EXPORT_API: '/api/contract/export',
  // 收款合同
  REMIND_EXPORT_API: '/api/remind_contract/export',
  // 成本管理列表
  COST_EXPORT_API: '/api/contract_cost/export',
  // 合同已审批
  CONTRACT_HISTROY_EXPORT_API: '/api/contract_history/export',
  // 开票管理列表
  INVOICE_EXPORT_API: '/api/invoice/export',
  // 开票公司列表
  INVOICE_OCOMPANY_EXPORT_API: '/api/invoice_company/export',
  // 收款
  RECEIPT_EXPORT_API: '/api/invoice_receipt/export',
  // 开票已审批
  INVOICE_HISTROY_EXPORT_API: '/api/invoice_history/export',
  // 付款
  PAYMENT_EXPORT_API: '/api/payment/export',
  // 付款人
  PAYEE_EXPORT_API: '/api/payment_payee/export',
  // 付款已审批
  PAYEE_HISTROY_EXPORT_API: '/api/payment_history/export',
  // 需求申请
  DEMAND_APPLY_EXPORT_API: '/api/demand_applications/export',
  // 需求修改
  DEMAND_MODIFY_EXPORT_API: '/api/demand_modifies/export',
  // 库存明细
  LOCATION_PRODUCT_EXPORT_API: '/api/location_product/export',
  // 调拨记录
  RECORD_EXPORT_API: '/api/erp_warehouse_change/export',
  // 仓库
  STORAGE_EXPORT_API: '/api/erp_warehouse/export',
  // 库位
  LOCATION_EXPORT_API: '/api/erp_location/export',
  // 产品
  PRODUCT_EXPORT_API: '/api/erp_product/export',
  // 公司
  COMAPNY_EXPORT_API: '/api/companies/export'
}
